# Generated by Django 3.2.12 on 2022-04-01 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'ADDRESS_INFO',
                'ordering': ('pincode',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(22), django.core.validators.MaxValueValidator(58)])),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('photo', models.ImageField(upload_to='resources/')),
            ],
        ),
    ]
